Adiciona exercicio refatorado do cartao de credito
aceleradora-TW/exercicios-js-twu pull request #1
Opened 2018-04-12 21:05 UTC by AndreiRupertti

Tentei refazer o exercício de forma mais concisa, foi o melhor que consegui mas percebi que ainda tem variáveis não-constantes, algumas funções não dependem só de seus parâmetros entre outras coisas. Algum dos mentores se importaria de fazer um review do código?

2018-04-12 21:38 UTC, ghidorsi commented on validadteCardNumber_Andrei.js
> +  const arrayDeChar = card.split('')
`arrayDeChar` não é um bom nome aqui por dois motivos. Está em portugês enquanto o resto do código tá em inglês, e por que não me diz nada do que tem de conteúdo dentro dessa variável.

2018-04-12 21:40 UTC, ghidorsi commented on validadteCardNumber_Andrei.js
> +    inicialDigits: [51,52,54,55],
Aqui seria `initial` ao invés de inicial.

2018-04-12 21:44 UTC, ghidorsi commented on validadteCardNumber_Andrei.js
> +function validFirtDigits (card, digits) {
`Firt` seria `First` neste caso?

2018-04-12 21:50 UTC, yrachid requested changes

2018-04-12 21:50 UTC, othman853 commented on validadteCardNumber_Andrei.js
> +    inicialDigits: [34,37],
`initial`?

2018-04-12 21:53 UTC, yrachid requested changes

2018-04-12 21:53 UTC, othman853 commented on validadteCardNumber_Andrei.js
> +    name: 'AMEX',
E se a construção desses objetos `cardType` fosse feita por uma função? Evitaria duplicações:

```javascript
const cardType = (name, initialDigits, length) => ({name, initialDigitis, length})

const cardTypes = {
  amex: cardType('AMEX', [34, 37], 15).
  // ...
}
```
Outro ponto. Porque `cardTypes`  é um objeto? Não poderia ser uma lista, já que cada cardType possui um atributo `name`?

2018-04-12 21:54 UTC, ghidorsi requested changes

2018-04-12 21:54 UTC, ghidorsi commented on validadteCardNumber_Andrei.js
> +  amex: {
Eu faria diferente, e evitaria uma conversão de array mais pra frente. Eu declararia `cardTypes` como um array, e dentro deles só o objeto de cada cartão, já que a `key` aqui não está sendo usada em momento algum.

2018-04-12 21:54 UTC, ghidorsi commented on validadteCardNumber_Andrei.js
> +  Object.values(cardTypes).some((cardType) => {
Essa conversão não seria necessária se o array já existisse no começo.

2018-04-12 21:54 UTC, ghidorsi commented on validadteCardNumber_Andrei.js
> +  return typeof targetLength === 'object'
Eu não sei, mas comparar typeof me parece um code smell. Alguma opnião @othman853? Eu teria colocado todos os digitos dentro de um array, mesmo que fosse somente um e somente utilizar `includes` ou `some`.

2018-04-12 21:57 UTC, yrachid requested changes

2018-04-12 21:57 UTC, othman853 commented on validadteCardNumber_Andrei.js
> +  Object.values(cardTypes).some((cardType) => {
Como mencionei anteriormente, será que essa parte não ficaria mais legível se `cardTypes` fosse um array?

2018-04-12 21:57 UTC, othman853 commented on validadteCardNumber_Andrei.js
> +const cardTypes = {
Acho que tem um typo no nome do arquivo. Acredito que deveria ser `validateCardNumber_Andrei.js`

2018-04-12 21:58 UTC, ghidorsi commented on validadteCardNumber_Andrei.js
> +  amex: {
Melhor ainda com a ideia do construtor do @othman853 :)

2018-04-12 22:02 UTC, yrachid requested changes

2018-04-12 22:02 UTC, othman853 commented on validadteCardNumber_Andrei.js
> +    inicialDigits: 6011,
Por uma questão de consistência, eu manteria `initialDigits` e `length` como sendo sempre de um mesmo tipo de dados (array, neste caso), independentemente da quantidade de itens deste array. Isso remove a necessidade de fazer checks com `typeof` e também de termos problemas de funções indefinidas. `forEach is not a function`, por exemplo.

2018-04-12 22:06 UTC, yrachid requested changes

2018-04-12 22:06 UTC, othman853 commented on validadteCardNumber_Andrei.js
> +  return typeof targetLength === 'object'
Nessa situação, estamos usando `typeof targetLength === 'object'`. Levei bastante tempo para entender que isso estava verificando se targetLength era ou não um array, para poder usar `.includes`. Como mencionei anteriormente, se tivermos os dados num mesmo tipo, não teremos esse problema. Acredito que seja a melhor forma de remover essa verificação, já que temos controle sobre nossos dados (nós é quem criamos os cardTypes).

Faz sentido @AndreiRupertti ?

2018-04-12 22:06 UTC, othman853 commented on validadteCardNumber_Andrei.js
> +    let num = parseInt(charNum)
Acho que não precisa de `parseInt` aqui:

![screenshot from 2018-04-12 19-05-11](https://user-images.githubusercontent.com/4705127/38706685-759cdc64-3e84-11e8-851c-7af2e2c7887f.png)

```
¯\_(ツ)_/¯
```

2018-04-12 22:13 UTC, yrachid requested changes

2018-04-12 22:13 UTC, othman853 commented on validadteCardNumber_Andrei.js
> +    if (index % 2 == 0)
Extrair isso para `isOdd` para deixar mais legível?

2018-04-12 22:13 UTC, othman853 commented on validadteCardNumber_Andrei.js
> +  arrayDeChar.forEach((charNum, index) => {
A lógica principal do algoritmo está neste callback anônimo. Faria sentido extrair essa função e dar um nome à ela?

2018-04-12 22:13 UTC, othman853 commented on validadteCardNumber_Andrei.js
> +    ? result += num
A identação está quebrada aqui:

```
num < 9
  ? result += num
  : result += num -9
```

2018-04-12 22:13 UTC, othman853 commented on validadteCardNumber_Andrei.js
> +  const cardNumber = card.split(' ').join('')
`card.replace(/\s/g, '')`?

2018-04-12 22:13 UTC, othman853 commented on validadteCardNumber_Andrei.js
> +  const cardNumber = card.split(' ').join('')
Poderíamos extrair isso para uma função por legibilidade?

```javascript
const removeBlankSpaces = (number) => number.replace(/\s/g, '')
```

2018-04-12 22:22 UTC, yrachid requested changes

2018-04-12 22:22 UTC, yrachid commented on validadteCardNumber_Andrei.js
> +  Object.values(cardTypes).some((cardType) => {
Aqui o `.some` está sendo usado como se fosse um `.forEach`, apenas percorremos o array fazendo um if e alterando o valor de `finalMessage`. Tenho as seguintes sugestões neste caso:

* Trocar o `some` por `find` para encontrar o primeiro cartão de credito válido

Se existe pelo menos um cartão de crédito válido, então a mensagem final mostra esse cartão, senão, mostra "cartão de crédito inválido". Mais ou menos o seguinte:

```javascript
const typeFor = number => type => validCardType(number, type) && validLuhn(number)

const cardType = cardTypes.find(typeFor(number))

const finalMessage = cardType
  ? `CardType Accepted: ${cardType.name}. Card Number also Valid!`
  : 'Invalid'
```

Existe um outro problema nesta lógica, que é o fato de buscarmos o tipo do cartão e também verificarmos que seu número é válido. Talvez fizesse sentido separar estas duas verificações. Faz sentido?

2018-04-12 22:25 UTC, yrachid requested changes

2018-04-12 22:25 UTC, othman853 commented on validadteCardNumber_Andrei.js
> +  return validFirtDigits(card, cardType.inicialDigits)
E se?

```javascript
const hasValidType = (card, {initialDigits, length}) => 
  validFirstDigits(card, initialDigits) && validLength(card, length)
```

2018-04-12 22:33 UTC, othman853 commented on validadteCardNumber_Andrei.js
> +  return typeof targetLength === 'object'
Alternativamente, se quiseres manter os diferentes tipos, podes utilizar `Array.isArray`:

![screenshot from 2018-04-12 19-32-49](https://user-images.githubusercontent.com/4705127/38707593-58b3ff70-3e88-11e8-8d62-90cdd597f40e.png)

2018-04-12 22:35 UTC, othman853 commented on validadteCardNumber_Andrei.js
> +    inicialDigits: [51,52,54,55],
Como temos uma função `validFirstDigits`, creio que um nome mais consistente seria `firstDigits`.

Faz sentido?

2018-04-12 23:12 UTC, ghidorsi commented on validadteCardNumber_Andrei.js
> +    if (index % 2 == 0)
Você quis dizer: `isPair`?

2018-04-12 23:13 UTC, ghidorsi commented on validadteCardNumber_Andrei.js
> +  return validFirtDigits(card, cardType.inicialDigits)
Caso tu não tenha entendido o `{initialDigits, length})` podemos conversar amanhã sobre.

2018-04-12 23:24 UTC, yrachid commented
Compilei na implementação seguinte algumas sugestões que havia pensado.

```javascript
const cardNumber = (rawNumber = '') => ({
  asIntArray: () => (rawNumber.replace(/\s/g, '') || '').split('').map(digit => parseInt(digit)),
  firstSlug: () => (rawNumber.split(' ')[0]) || '',
  length: () => (rawNumber.replace(/\s/g, '') || '').length
})

const cardType = (name, firstDigits, allowedLengths) => ({
  name,
  firstDigits,
  allowedLengths
})

const UNKNOWN_CARD = {
  name: 'UNKNOWN'
}

const cardTypes = [
  cardType('Amex', [34, 37], [15]),
  cardType('Discover', [6011], [16]),
  cardType('MasterCard', [51, 52, 54, 55], [16]),
  cardType('Visa', [4], [13, 16]),
]

const byFirstDigits = (number) => type => {
  const containingFirstDigits = (digits) => number
    .firstSlug()
    .startsWith(digits.toString())

  return type
  .firstDigits
  .find(containingFirstDigits)
}

const byLength = (number) => type => type
  .allowedLengths
  .includes(number.length())

const findCardType = (number) => cardTypes
  .filter(byFirstDigits(number))
  .find(byLength(number))
  || UNKNOWN_CARD

const calculateLuhnDigit = (digit, index) => {
  const isOdd = digit % 2 === 0

  const positionallyDoubledDigit = isOdd
    ? Math.pow(digit, 2)
    : digit

  return positionallyDoubledDigit < 9
    ? positionallyDoubledDigit
    : positionallyDoubledDigit - 9
}

const luhnValueOf = (number) => number
  .asIntArray()
  .reduce((result, digit, digitIndex) =>
    result + calculateLuhnDigit(digit, digitIndex))

const isValidLuhnNumber = (number) => luhnValueOf(number) % 10 === 0

const card = cardNumber('5108 0412 3456 7893')

console.log('Is valid luhn number: ', isValidLuhnNumber(card))
console.log('Card type: ', findCardType(card).name)
```


__Bônus:__ Aproveitando que estamos fazendo exercícios, menciono que não testei esta solução então provavelmente haverá(ão) bug(s). Eu com certeza sei que existe pelo menos um bug nesta implementação. Qual seria ele? :stuck_out_tongue: 

O que pensa(m)?

2018-04-13 02:42 UTC, othman853 commented on validadteCardNumber_Andrei.js
> +    if (index % 2 == 0)
isEven, na verdade, heheheheh. Valeu :p

2020-05-19 15:46 UTC, closed without merging